# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('affairal_app', '0004_affairaluser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='affairaluser',
            name='reg_id',
            field=models.TextField(default=uuid.UUID('d5763a5b-31a2-4b6f-947f-9f660ec39c04')),
        ),
    ]
